markers = ['or', 'og', 'ob', 'oc', 'om', 'oy', 'ob', 'ow', ...
           '+r', '+g', '+b', '+c', '+m', '+y', '+b', '+w', ...
           '*r', '*g', '*b', '*c', '*m', '*y', '*b', '*w', ...
           'xr', 'xg', 'xb', 'xc', 'xm', 'xy', 'xb', 'xw']
%line style: -, --, :, -.
%marker: o, +, *, x, _, |, s, d, ^, v, >, <, p, h
%color: r, g, b, c, m, y, b, w